<a href="https://colab.research.google.com/github/bonareri/Python-Data-Analysis/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [2]:
import numpy as np

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [7]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
with_border = np.zeros((a.shape[0] + 2, a.shape[1] + 2), dtype=a.dtype); with_border[1:-1, 1:-1] = a
print(with_border)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [8]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [10]:
matrix = np.zeros((5, 5))
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [11]:
matrix = np.zeros((8, 8))
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [13]:
shape = (6, 7, 8)
flat_index = 99
unravel_index = np.unravel_index(flat_index, shape)
print(unravel_index)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [14]:
matrix = np.array([[0, 1], [1, 0]])
checkerboard = np.tile(matrix, (4, 4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [16]:
rand_matrix = np.random.rand(5, 5)
normalized_matrix = (rand_matrix - np.mean(rand_matrix)) / np.std(rand_matrix)
print(normalized_matrix)


[[-1.37055036  1.30740435 -0.86331431 -0.7972352  -1.54449813]
 [ 0.6908334   0.71286045 -0.18077332  1.1049751  -0.9025054 ]
 [-0.45496138  0.17643973 -1.29722948 -1.5605933   0.51125748]
 [-0.60349782 -1.14406859  1.65428114  0.8984513   0.06483395]
 [ 1.36112165  0.24624985  1.21009878  1.12207211 -0.34165199]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [2]:
import numpy as np

color_dtype = np.dtype([
    ('red', np.uint8),
    ('green', np.uint8),
    ('blue', np.uint8),
    ('alpha', np.uint8)
])

colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color_dtype)
print(colors)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [5]:
matrix_1 = np.random.rand(5, 3)
matrix_2 = np.random.rand(3, 2)
result = np.dot(matrix_1, matrix_2)
print(matrix_1)
print(matrix_2)
print(result)

[[0.71064976 0.82398578 0.60828696]
 [0.14699532 0.57146565 0.28515558]
 [0.03454868 0.04309862 0.55161784]
 [0.13533239 0.5066049  0.98107307]
 [0.41328193 0.89633328 0.60449725]]
[[0.38481014 0.82695944]
 [0.15462947 0.45697361]
 [0.88216253 0.47490739]]
[[0.93748568 1.25309826]
 [0.39648429 0.51812638]
 [0.50657559 0.31023268]
 [0.99587922 0.80933831]
 [0.83089944 1.03844826]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [6]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array[(array > 3) & (array < 8)] *= -1
print(array)

[ 1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [7]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal?
(★☆☆)
```python
Z**Z     
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

The legal expressions are:

Z**Z
2 << Z >> 2
1j*Z
Z/1/1
The illegal expressions are:

Z <- Z
Z<Z>Z

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [8]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-8-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-8-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-8-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [9]:
arr = np.array([1.2, 2.5, -1.2, -2.5, 0.0])
rounded_arr = np.ceil(arr)
print(rounded_arr)

[ 2.  3. -1. -2.  0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [10]:
array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([3, 4, 5, 6, 7])
common_values = np.intersect1d(array_1, array_2)
print(common_values)

[3 4 5]
