<a href="https://colab.research.google.com/github/bonareri/Python-Data-Analysis/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python Data Analysis

In [1]:
!pip install numpy


In [3]:
import numpy as np

In [4]:
np.__version__

'1.26.4'

In [5]:
np?

In [6]:
x = [1, 2, 3, 4, 5]
print(type (x))
x = np.array(x)

print(type(x))


<class 'list'>
<class 'numpy.ndarray'>


In [7]:
a = [1,2,'Ann', True, False]
b = np.array(a)
print(b)
print(type(b))

['1' '2' 'Ann' 'True' 'False']
<class 'numpy.ndarray'>


In [9]:
arr = np.arange(10)
print(arr)
print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [12]:
#Start, stop
arr = np.arange(2, 10, 3)
print(arr)
print(type(arr))

[2 5 8]
<class 'numpy.ndarray'>


In [13]:
#linspace
arr = np.linspace(1, 4, 6)
print(arr)
print(type(arr))

[1.  1.6 2.2 2.8 3.4 4. ]
<class 'numpy.ndarray'>


In [14]:
# prompt: random

# random numbers
arr = np.random.rand(5)
print(arr)
print(type(arr))
# random integers between 1 and 10
arr = np.random.randint(1, 10, size=5)
print(arr)
print(type(arr))
# random numbers from a normal distribution
arr = np.random.randn(5)
print(arr)
print(type(arr))


[0.65768929 0.37691433 0.48361878 0.81617282 0.5368454 ]
<class 'numpy.ndarray'>
[7 4 5 2 7]
<class 'numpy.ndarray'>
[-1.15832541  0.66729607  0.04426049 -0.55642378 -1.5101505 ]
<class 'numpy.ndarray'>


In [16]:
#Generate a random float between 0 and 1
arr = np.random.random((2,3))
print(arr)
print(type(arr))
#

[[0.80322394 0.81274165 0.19209085]
 [0.06383352 0.94510259 0.31040146]]
<class 'numpy.ndarray'>


In [17]:
# random numbers
arr = np.random.rand(5)
print(arr)
print(type(arr))

[0.27350376 0.30064721 0.80549423 0.6674767  0.78535482]
<class 'numpy.ndarray'>


Numpy Attributes

In [18]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [19]:
mat = np.array([[[1,2,3],[3,4,5],[6,7,8]]], dtype=int)
print(mat)

[[[1 2 3]
  [3 4 5]
  [6 7 8]]]


In [20]:
mat.ndim

3

In [21]:
arr = np.random.random(5, 20 (5, 4, 5))

<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<ipython-input-21-0918bba28de4>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  arr = np.random.random(5, 20 (5, 4, 5))


TypeError: 'int' object is not callable

In [24]:
#Integer Types
int_arr = np.array([1, 2, 3], dtype=np.int32)
print(type(int_arr))
print(int_arr)
print(int_arr.dtype)
print("\n")

#Float Types
float_arr = np.array([1, 2, 3], dtype=np.float64)
print(type(float_arr))
print(float_arr)
print(float_arr.dtype)
print("\n")
#

<class 'numpy.ndarray'>
[1 2 3]
int32


<class 'numpy.ndarray'>
[1. 2. 3.]
float64




In [27]:
#Giving a new shape to an array without changing its data

arr = np.array([[1,2,3,7,8], [4,5,6,9,10]])
print(f"Shape : {arr.shape}")
print(arr)
print("\n")

arr2 = arr.reshape(5,2)
print(f"Arr 2 Shape : {arr2.shape}")
print(arr2)


Shape : (2, 5)
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


Arr 2 Shape : (5, 2)
[[ 1  2]
 [ 3  7]
 [ 8  4]
 [ 5  6]
 [ 9 10]]


In [28]:
#flatens the array into a 1 D
arr3 = arr.reshape(-1)
print(f"Arr 3 Shape : {arr3.shape}")
print(arr3)

Arr 3 Shape : (10,)
[ 1  2  3  7  8  4  5  6  9 10]


In [29]:
#creates a row vecror
arr3 = arr.reshape(1, -1)
print(f"Arr 3 Shape : {arr3.shape}")
print(arr3)

Arr 3 Shape : (1, 10)
[[ 1  2  3  7  8  4  5  6  9 10]]


In [30]:
#creates a column vector
arr3 = arr.reshape(-1, 1)
print(f"Arr 3 Shape : {arr3.shape}")
print(arr3)

Arr 3 Shape : (10, 1)
[[ 1]
 [ 2]
 [ 3]
 [ 7]
 [ 8]
 [ 4]
 [ 5]
 [ 6]
 [ 9]
 [10]]
