<a href="https://colab.research.google.com/github/bonareri/Python-Data-Analysis/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [1]:
import warnings
import numpy as np

#ignore all warnings
warnings.filterwarnings('ignore')

#example of code that might give a warning
np.array([1,2,3])/0


array([inf, inf, inf])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
np.sqrt(-1) will produce a warning and result in nan (Not a Number) because the standard numpy.sqrt function is intended for real numbers and does not handle negative inputs as complex numbers.
np.emath.sqrt(-1), on the other hand, will return a complex number because np.emath.sqrt (from the numpy.emath module) is designed to handle complex numbers. So np.emath.sqrt(-1) will output 1j, which is the imaginary unit.
```

In [2]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [3]:
#Todays date
today = np.datetime64('today', 'D')

#Yesterdays date
yesterday = today - np.timedelta64(1, 'D')

#Tomorrows date
tomorrow = today + np.timedelta64(1, 'D')

print("Today's date:", today)
print("Yesterday's date:", yesterday)
print("Tomorrow's date:", tomorrow)


Today's date: 2024-10-30
Yesterday's date: 2024-10-29
Tomorrow's date: 2024-10-31


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [4]:
#Defines start and end of dates in July 2016
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')

#Generate all dates within this range
july_2016_dates = np.arange(start_date, end_date, dtype='datetime64[D]')

print(july_2016_dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [8]:
# Example arrays
A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6], dtype=float)

# Compute A + B and store in A
A += B

# Multiply by -original_A/2
original_A = A - B
A *= -original_A / 2

print(A)

[ -2.5  -7.  -13.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [9]:
# Generate a random array of positive numbers
random_array = np.random.rand(10) * 100  # Random numbers between 0 and 100

# Using np.floor()
integer_part_floor = np.floor(random_array).astype(int)

print("Original Array:", random_array)
print("Integer Part using np.floor():", integer_part_floor)


Original Array: [47.32306709 93.40255091  7.75202925 61.92893526 46.5704568  23.7638914
 24.74072533 70.9284335  69.55699091 15.66653408]
Integer Part using np.floor(): [47 93  7 61 46 23 24 70 69 15]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [11]:
matrix = np.tile(np.arange(0, 5), (5, 1))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [13]:
#creating the function
def generator_function(n):
    for _ in range(n):
        yield np.random.randint(1, 100)

gen = generator_function(10)

#using the function to create an array
array = np.array(list(gen))

print("Generated array:", array)


Generated array: [23 69 94  8 86 49 84 12 40 20]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [15]:
vector = np.random.uniform(0, 1, size=10)

print(vector)


[0.17815677 0.85880207 0.9836539  0.39506985 0.9467114  0.58170192
 0.21736346 0.48325741 0.39072392 0.2072666 ]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [20]:
random_vector = np.random.rand(10)

sorted_vector = np.sort(random_vector)

print("Rndom Vector :",random_vector)
print("Sorted Vector :", sorted_vector)

Rndom Vector : [0.68624662 0.06351424 0.4523015  0.97881948 0.59014065 0.68431183
 0.17401809 0.45472539 0.61141234 0.51028339]
Sorted Vector : [0.06351424 0.17401809 0.4523015  0.45472539 0.51028339 0.59014065
 0.61141234 0.68431183 0.68624662 0.97881948]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [21]:
small_array = np.array([1, 2, 3, 4, 5])

# Using built-in sum
result = sum(small_array)
print("Sum using built-in sum:", result)


Sum using built-in sum: 15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [22]:
A = np.random.rand(5)  # Random array of size 5
B = np.random.rand(5)  # Another random array of size 5

#Checking if the arrays are equal
are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)
print("Are A and B equal?", are_equal)


Array A: [0.90464301 0.39854976 0.03431627 0.03964019 0.91644312]
Array B: [0.58068928 0.997978   0.83724863 0.31362283 0.58244002]
Are A and B equal? False


#### 43. Make an array immutable (read-only) (★★☆)

In [23]:
array = np.array([1, 2, 3, 4, 5])

#Making the array read-only
array.flags.writeable = False

# Displaying the array and its writeable status
print("Array:", array)
print("Is the array writable?", array.flags.writeable)

#Trying to modify the array (this will raise an error)
try:
    array[0] = 10  # Attempt to modify the array
except ValueError as e:
    print("Error:", e)


Array: [1 2 3 4 5]
Is the array writable? False
Error: assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [24]:
#Generate a random 10x2 matrix representing Cartesian coordinates
cartesian_coords = np.random.rand(10, 2)  # Random values between 0 and 1

# Extract x and y coordinates
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]

# Calculate polar coordinates
r = np.sqrt(x**2 + y**2)  # Calculate the radius
theta = np.arctan2(y, x)  # Calculate the angle in radians

# Combine r and theta into a single array
polar_coords = np.column_stack((r, theta))

# Display results
print("Cartesian Coordinates:\n", cartesian_coords)
print("\nPolar Coordinates (r, θ):\n", polar_coords)


Cartesian Coordinates:
 [[0.55034366 0.35379031]
 [0.07381896 0.38124192]
 [0.78349645 0.70279951]
 [0.98541089 0.52197022]
 [0.7250379  0.8964666 ]
 [0.8818217  0.59871567]
 [0.00570657 0.87276166]
 [0.97214462 0.59292406]
 [0.35090896 0.11553689]
 [0.8578311  0.16194596]]

Polar Coordinates (r, θ):
 [[0.65425204 0.57133485]
 [0.38832285 1.37953551]
 [1.05251786 0.73115743]
 [1.11511772 0.48712282]
 [1.15296675 0.89072889]
 [1.06586583 0.59646051]
 [0.87278031 1.5642579 ]
 [1.13869403 0.54767692]
 [0.36943994 0.31807137]
 [0.87298378 0.18658938]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [26]:
random_vector = np.random.rand(10)  # Random vector of size 10

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Original Vector:", random_vector)
print("Vector with Maximum Value Replaced by 0:", random_vector)

Original Vector: [0.65834706 0.30028958 0.42204545 0.73199279 0.         0.67807928
 0.34021736 0.57683974 0.31782812 0.0333056 ]
Vector with Maximum Value Replaced by 0: [0.65834706 0.30028958 0.42204545 0.73199279 0.         0.67807928
 0.34021736 0.57683974 0.31782812 0.0333056 ]
